[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@localhost:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.mainnet]
shard = "primary"
provider = [
    { label = "bootstrap", details = { type = "web3", url = "$RPC_NODE", features = [ "archive" ] }},
    { label = "firehose", details = { type = "firehose", url = "$SUBSTREAMS_ENDPOINT", token = "$FIREHOSE_API_TOKEN" }},
    { label = "substreams", details = { type = "substreams", url = "$SUBSTREAMS_ENDPOINT", token = "$SUBSTREAMS_API_TOKEN" }},
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]
