[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@localhost:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.mainnet]
shard = "primary"
protocol = "substreams"
provider = [
    { label = "substreams-provider-mainnet", details = { type = "firehose", url = "http://localhost:9000", token = "$STREAMING_FAST_API_TOKEN" }},
]


[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]
