[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@localhost:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.near-testnet]
shard = "primary"
protocol = "near"
provider = [
  { label = "near-testnet", details = { type = "firehose", url = "$FIREHOSE_ENDPOINT", token = "$STREAMING_FAST_API_TOKEN" }},
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]