[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@localhost:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.matic]
shard = "primary"
protocol = "ethereum"
provider = [
  { label = "firehose", details = { type = "firehose", url = "$FIREHOSE_ENDPOINT", token = "$STREAMING_FAST_API_TOKEN", features = [ "filters" ] }},
  { label = "calls", details = { type = "web3", url = "$POLYGON_MAINNET_RPC_URL", features = [ "archive" ] }},
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]
